# Generated by Django 4.2.7 on 2024-01-25 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_manslothes_womanclothes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Computers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('img', models.ImageField(upload_to='image/')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=200)),
                ('number', models.IntegerField()),
                ('massage', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Mansclothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField()),
                ('img', models.ImageField(upload_to='image/')),
                ('status', models.TextField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Manslothes',
        ),
        migrations.RemoveField(
            model_name='womanclothes',
            name='static',
        ),
        migrations.AddField(
            model_name='womanclothes',
            name='bio',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
